### ISSUE TITLE
process.py detects false satellites at edge of frames

### ISSUE THREAD

**Issue by interplanetarychris** [cbassa/stvid#54] opened 2019-11-30 20:46 UTC
I'm noticing a regular occurrence of `process.py` identifying false-positive satellites at the edge of frame. 

Some examples within my process flow:
- 2019-11-30T02/45/27.879_88716
- 2019-11-30T02/53/38.834_24292

**Comment by cbassa** [comment] 2022-08-25 16:46
This is caused by the identification method extrapolating from the detected track to the endpoints from the start to the end of the exposure. For short tracks that enter or exit the frame, the extrapolation is too uncertain and the matching to predictions fails. This should be fixed by the `dev` branch that interpolates the predictions to the timestamps of the observed track.

**Closed by cbassa** 2022-08-25 16:46 UTC
Labels: bug
